sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx
  
haxe:
  - development
  
install:
  - haxelib install travix
  - haxelib run travix install

script:
  - haxelib run travix neko
  - haxelib run travix interp
  - haxelib run travix node
  - haxelib run travix php 
  - haxelib run travix cs
  - haxelib run travix java
  - haxelib run travix cpp -lib hxcpp
